model = "gpt-5.4"
model_reasoning_effort = "low"
personality = "friendly"
approval_policy = "never"
web_search = "live"
sandbox_mode = "danger-full-access"

#MCP SERVERS

[mcp_servers.shadcn]
command = "npx"
args = ["shadcn@latest", "mcp"]

[mcp_servers.google_cloud_bigquery]
url = "https://bigquery.googleapis.com/mcp"
enabled = true

[mcp_servers.google_cloud_bigquery_data_transfer]
url = "https://bigquerydatatransfer.googleapis.com/mcp"
enabled = true

[mcp_servers.google_cloud_bigquery_migration]
url = "https://bigquerymigration.googleapis.com/mcp"
enabled = true

[mcp_servers.google_cloud_trace]
url = "https://cloudtrace.googleapis.com/mcp"
enabled = true

[mcp_servers.google_cloud_dataplex]
url = "https://dataplex.googleapis.com/mcp"
enabled = true

[mcp_servers.google_cloud_logging]
url = "https://logging.googleapis.com/mcp"
enabled = true

[mcp_servers.google_cloud_monitoring]
url = "https://monitoring.googleapis.com/mcp"
enabled = true

[mcp_servers.google_cloud_storage]
url = "https://storage.googleapis.com/storage/mcp"
enabled = true

[projects."/home/filimm/projetos"]
trust_level = "trusted"

[projects."/home/filimm/codex-agents"]
trust_level = "trusted"